/* ================================================================
   ZENITH TRAVEL AND TOURS — data.js
   Central data store. Edit via admin.html or directly here.
   All pages read from localStorage (if admin saved) or this default.
================================================================ */

const ZENITH_DEFAULT_DATA = {

  /* ---- SITE META ---- */
  meta: {
    phone: "+33 7 44 98 03 42",
    email: "contact@zenith-madagascar.com",
    whatsapp: "33744980342",
    instagram: "#",
    facebook: "#",
    tripadvisor: "#"
  },

  /* ================================================================
     TRANSLATIONS — FR / EN / MG (Malagasy)
  ================================================================ */
  i18n: {
    fr: {
      nav_about:     "À propos",
      nav_circuits:  "Circuits",
      nav_grouped:   "Voyages groupes",
      nav_services:  "Services",
      nav_reviews:   "Avis",
      nav_contact:   "Contact",
      nav_quote:     "Devis gratuit",
      hero_tag:      "Agence spécialisée Madagascar",
      hero_h1a:      "Votre aventure",
      hero_h1b:      "malgache,",
      hero_h1c:      "sur mesure",
      hero_sub:      "Une passionnée de la Grande Île à votre service — en français, en anglais et en malgache.",
      hero_cta1:     "Demander un devis",
      hero_cta2:     "Voir les circuits",
      stat1_n: "+200", stat1_l: "Voyages réalisés",
      stat2_n: "15+",  stat2_l: "Destinations",
      stat3_n: "3",    stat3_l: "Langues parlées",
      stat4_n: "100%", stat4_l: "Sur mesure",
      about_tag:     "À propos",
      about_h2a:     "La Grande Île,",
      about_h2b:     "comme si vous",
      about_h2c:     "y étiez née",
      about_p1:      "Derrière Zenith Travel and Tours, il y a une seule personne : une guide et organisatrice trilingue, originaire de Nosy Be, passionnée jusqu'à la moelle par chaque recoin de la Grande Île. Pas une agence anonyme — une relation directe, attentive, personnelle.",
      about_p2:      "Forte de dix ans d'expérience à concevoir des voyages sur mesure pour des voyageurs francophones et anglophones exigeants, elle façonne des itinéraires qui respectent les communautés locales, préservent les paysages et laissent des souvenirs à vie.",
      about_quote:   "Madagascar mérite une découverte lente, attentive et sincère. Je suis là pour que vous la viviez vraiment.",
      about_cite:    "— Votre guide Zenith",
      val1_title:    "Tourisme responsable", val1_sub: "Respect des communautés et de la biodiversité",
      val2_title:    "Sécurité garantie",    val2_sub: "Véhicules contrôlés, chauffeurs de confiance",
      val3_title:    "100% sur mesure",      val3_sub: "Conçu pour vous, pas pour un groupe",
      val4_title:    "Suivi personnel",      val4_sub: "Un interlocuteur unique, du devis au retour",
      circuits_tag:  "Circuits sur mesure",
      circuits_h2:   "Programmes emblématiques",
      circuits_sub:  "À personnaliser selon vos envies, votre rythme, votre budget",
      see_circuit:   "Voir le circuit",
      from_label:    "À partir de",
      per_person:    "/personne",
      grouped_tag:   "Dates fixes · Places limitées",
      grouped_h2:    "Voyages organisés",
      grouped_sub:   "Partez en petit groupe à prix réduit — programme fixe, ambiance garantie",
      places_left:   "places disponibles",
      places_few:    "place restante",
      book_now:      "Réserver",
      group_price:   "Prix groupe",
      group_incl:    "tout inclus",
      services_tag:  "Ce qui est inclus",
      services_h2:   "Tout est prévu pour vous",
      services_sub:  "Un accompagnement complet, de votre premier message jusqu'au retour",
      svc1_h: "Transport 4×4 avec chauffeur", svc1_p: "Toyota Land Cruiser récents, chauffeurs bilingues de confiance. Toutes les pistes de la Grande Île accessibles.",
      svc2_h: "Hébergements sélectionnés",   svc2_p: "Lodges de charme, écolodges en brousse — pré-réservés, qualité vérifiée personnellement.",
      svc3_h: "Guide trilingue FR/EN/MGA",   svc3_p: "Un interlocuteur unique qui parle votre langue et celle des Malgaches — pour une immersion authentique.",
      svc4_h: "Itinéraires personnalisés",   svc4_p: "Chaque voyage est pensé avec vous : durée, rythme, activités, budget — sans frais cachés.",
      reviews_tag:   "Ils sont revenus ravis",
      reviews_h2:    "Ce que disent mes voyageurs",
      cta_h2:        "Prêt(e) à vivre votre Madagascar ?",
      cta_sub:       "Contactez-moi directement — le devis est gratuit et sans engagement.",
      cta_btn:       "Demander mon devis",
      contact_tag:   "Me contacter",
      contact_h2a:   "Construisons",
      contact_h2b:   "votre voyage",
      contact_sub:   "Réponse garantie sous 24h — devis gratuit & sans engagement",
      form_h3:       "Demande de devis gratuit",
      form_intro:    "Remplissez ce formulaire et je vous réponds sous 24h avec une proposition personnalisée.",
      form_required: "Champ obligatoire",
      f_name:        "Nom complet", f_name_ph: "Jean Dupont",
      f_email:       "Email",       f_email_ph: "jean@exemple.fr",
      f_phone:       "Téléphone",   f_phone_ph: "+33 6 12 34 56 78",
      f_travelers:   "Nombre de voyageurs",
      f_date:        "Date de départ souhaitée",
      f_duration:    "Durée envisagée",
      f_circuit:     "Circuit d'intérêt",
      f_pref:        "Moyen de contact préféré",
      f_pref_email:  "Email", f_pref_wa: "WhatsApp", f_pref_call: "Appel",
      f_message:     "Message / précisions", f_message_ph: "Décrivez vos envies, contraintes, budget indicatif…",
      f_submit:      "Envoyer ma demande",
      f_success_h:   "Message envoyé !",
      f_success_p:   "Merci ! Je vous réponds sous 24h avec votre proposition personnalisée.",
      f_opt1: "1 personne", f_opt2: "2 personnes", f_opt3: "3–4 personnes", f_opt4: "5–8 personnes", f_opt5: "Groupe 9+",
      fd_opt1: "Moins de 7 jours", fd_opt2: "7–10 jours", fd_opt3: "11–14 jours", fd_opt4: "15–21 jours", fd_opt5: "Plus de 21 jours",
      footer_tagline: "Agence personnelle spécialisée Madagascar. Guide trilingue (FR/EN/MGA), originaire de Nosy Be, basée en France.",
      footer_circuits: "Circuits", footer_info: "Informations",
      footer_nl_h: "Restez inspiré(e)",
      footer_nl_p: "Recevez mes idées de circuits et nouvelles dates de voyages groupes.",
      footer_nl_ph: "votre@email.fr",
      footer_ml: "Mentions légales", footer_cgv: "CGV", footer_conf: "Confidentialité",
      copyright: "© 2026 Zenith Travel and Tours — Tous droits réservés.",
      back_circuits: "Tous les circuits",
      discover_also: "Découvrir aussi",
      other_circuits: "D'autres circuits Madagascar",
      grouped_also: "Vous souhaitez un circuit sur mesure ?",
      grouped_also_btn: "Demander un circuit sur mesure",
      lang_fr: "FR", lang_en: "EN", lang_mg: "MG"
    },

    en: {
      nav_about:     "About",
      nav_circuits:  "Tours",
      nav_grouped:   "Group trips",
      nav_services:  "Services",
      nav_reviews:   "Reviews",
      nav_contact:   "Contact",
      nav_quote:     "Free quote",
      hero_tag:      "Madagascar travel specialist",
      hero_h1a:      "Your Malagasy",
      hero_h1b:      "adventure,",
      hero_h1c:      "tailor-made",
      hero_sub:      "A Madagascar enthusiast at your service — in French, English and Malagasy.",
      hero_cta1:     "Request a quote",
      hero_cta2:     "See our tours",
      stat1_n: "+200", stat1_l: "Trips completed",
      stat2_n: "15+",  stat2_l: "Destinations",
      stat3_n: "3",    stat3_l: "Languages spoken",
      stat4_n: "100%", stat4_l: "Tailor-made",
      about_tag:     "About",
      about_h2a:     "The Big Island,",
      about_h2b:     "as if you were",
      about_h2c:     "born there",
      about_p1:      "Behind Zenith Travel and Tours is one person: a trilingual guide and travel organiser, originally from Nosy Be, deeply passionate about every corner of the Big Island. Not an anonymous agency — a direct, attentive and personal relationship.",
      about_p2:      "With ten years of experience designing bespoke trips for discerning French and English-speaking travellers, she crafts itineraries that respect local communities, preserve landscapes and create lifelong memories.",
      about_quote:   "Madagascar deserves to be discovered slowly, attentively and sincerely. I'm here to make sure you truly experience it.",
      about_cite:    "— Your Zenith guide",
      val1_title:    "Responsible tourism", val1_sub: "Respect for communities and biodiversity",
      val2_title:    "Safety guaranteed",    val2_sub: "Checked vehicles, trusted drivers",
      val3_title:    "100% tailor-made",     val3_sub: "Designed for you, not for a group",
      val4_title:    "Personal follow-up",   val4_sub: "One point of contact, from quote to return",
      circuits_tag:  "Tailor-made tours",
      circuits_h2:   "Signature programmes",
      circuits_sub:  "Customisable to your wishes, pace and budget",
      see_circuit:   "See the tour",
      from_label:    "From",
      per_person:    "/person",
      grouped_tag:   "Fixed dates · Limited places",
      grouped_h2:    "Group trips",
      grouped_sub:   "Travel in a small group at reduced prices — set programme, great atmosphere",
      places_left:   "places available",
      places_few:    "place left",
      book_now:      "Book now",
      group_price:   "Group price",
      group_incl:    "all inclusive",
      services_tag:  "What's included",
      services_h2:   "Everything is taken care of",
      services_sub:  "Complete support, from your first message to your return home",
      svc1_h: "4×4 transport with driver", svc1_p: "Recent Toyota Land Cruisers, trusted bilingual drivers. Every track on the Big Island accessible.",
      svc2_h: "Handpicked accommodation",  svc2_p: "Charming lodges, bush ecolodges — pre-booked with personally verified quality.",
      svc3_h: "Trilingual guide FR/EN/MGA",svc3_p: "One contact who speaks your language and the Malagasy people's — for authentic immersion.",
      svc4_h: "Personalised itineraries",  svc4_p: "Every trip is planned with you: duration, pace, activities, budget — no hidden fees.",
      reviews_tag:   "They came back delighted",
      reviews_h2:    "What my travellers say",
      cta_h2:        "Ready to live your Madagascar?",
      cta_sub:       "Contact me directly — the quote is free and with no obligation.",
      cta_btn:       "Request my quote",
      contact_tag:   "Get in touch",
      contact_h2a:   "Let's build",
      contact_h2b:   "your trip",
      contact_sub:   "Reply guaranteed within 24h — free quote, no obligation",
      form_h3:       "Free quote request",
      form_intro:    "Fill in this form and I'll reply within 24h with a personalised proposal.",
      form_required: "Required field",
      f_name:        "Full name",    f_name_ph: "John Smith",
      f_email:       "Email",        f_email_ph: "john@example.com",
      f_phone:       "Phone",        f_phone_ph: "+44 7700 900000",
      f_travelers:   "Number of travellers",
      f_date:        "Preferred departure date",
      f_duration:    "Planned duration",
      f_circuit:     "Tour of interest",
      f_pref:        "Preferred contact method",
      f_pref_email:  "Email", f_pref_wa: "WhatsApp", f_pref_call: "Phone call",
      f_message:     "Message / details", f_message_ph: "Describe your wishes, constraints, rough budget…",
      f_submit:      "Send my request",
      f_success_h:   "Message sent!",
      f_success_p:   "Thank you! I'll reply within 24h with your personalised proposal.",
      f_opt1: "1 person", f_opt2: "2 people", f_opt3: "3–4 people", f_opt4: "5–8 people", f_opt5: "Group 9+",
      fd_opt1: "Less than 7 days", fd_opt2: "7–10 days", fd_opt3: "11–14 days", fd_opt4: "15–21 days", fd_opt5: "More than 21 days",
      footer_tagline: "Personal Madagascar travel agency. Trilingual guide (FR/EN/MGA), originally from Nosy Be, based in France.",
      footer_circuits: "Tours", footer_info: "Information",
      footer_nl_h: "Stay inspired",
      footer_nl_p: "Receive itinerary ideas and new group trip dates.",
      footer_nl_ph: "your@email.com",
      footer_ml: "Legal notice", footer_cgv: "T&Cs", footer_conf: "Privacy policy",
      copyright: "© 2026 Zenith Travel and Tours — All rights reserved.",
      back_circuits: "All tours",
      discover_also: "Also discover",
      other_circuits: "More Madagascar tours",
      grouped_also: "Want a tailor-made tour?",
      grouped_also_btn: "Request a custom tour",
      lang_fr: "FR", lang_en: "EN", lang_mg: "MG"
    },

    mg: {
      nav_about:     "Momba anay",
      nav_circuits:  "Dian-tany",
      nav_grouped:   "Dia amim-pikambana",
      nav_services:  "Serivisy",
      nav_reviews:   "Hevitra",
      nav_contact:   "Fifandraisana",
      nav_quote:     "Fanontaniana maimaimpoana",
      hero_tag:      "Toeran'ny fanondranana any Madagasikara",
      hero_h1a:      "Ny dianao any",
      hero_h1b:      "Madagasikara,",
      hero_h1c:      "araka ny sitraponao",
      hero_sub:      "Olona iray tia an'i Madagasikara no ao antohanao — amin'ny teny frantsay, anglisy ary malagasy.",
      hero_cta1:     "Hangataka fanombanana",
      hero_cta2:     "Hijery ny dian-tany",
      stat1_n: "+200", stat1_l: "Dia vita",
      stat2_n: "15+",  stat2_l: "Toerana",
      stat3_n: "3",    stat3_l: "Fiteny resahina",
      stat4_n: "100%", stat4_l: "Voaomana ho anao",
      about_tag:     "Momba anay",
      about_h2a:     "Nosy Lehibe,",
      about_h2b:     "toy ny teraka",
      about_h2c:     "tao ianao",
      about_p1:      "Ao ambadik'i Zenith Travel and Tours dia olona iray ihany : mpitarika telo fiteny avy any Nosy Be, tia an'i Madagasikara manontolo. Tsy fikambana tsy misy endrika — fifandraisana mivantana, mana-pikarakara, manokana.",
      about_p2:      "Manana traikefa folo taona amin'ny fanamboarana dia an'ireo mpizaha tany miteny frantsay sy anglisy izy, mamorona làlana manaja ny fiaraha-monina eo an-toerana sy miaro ny tontolo iainana.",
      about_quote:   "Ny fijery an'i Madagasikara tokony ho slow, mailo ary marina. Eto aho mba hanaovanao izany marina.",
      about_cite:    "— Ny mpitarika Zenith",
      val1_title:    "Fizahantany mendrika", val1_sub: "Fanajana ny fiaraha-monina sy ny natiora",
      val2_title:    "Arontsaina ny arogantena",  val2_sub: "Fiara voafehy, mpamily matoky",
      val3_title:    "100% voaomana ho anao", val3_sub: "Natao ho anao, tsy ho vondron'olona",
      val4_title:    "Fanaraha-maso manokana", val4_sub: "Mpifandray tokana, hatramin'ny fanombanana ka hatramin'ny fiverenana",
      circuits_tag:  "Dian-tany araka ny sitrapo",
      circuits_h2:   "Programa malaza",
      circuits_sub:  "Azo ovana araka ny fanirianao, ny dinanao, ny tetibola",
      see_circuit:   "Hijery ny dian-tany",
      from_label:    "Manomboka",
      per_person:    "/olona",
      grouped_tag:   "Daty voafaritra · Toerana voafetra",
      grouped_h2:    "Dia amin'ny vondron'olona",
      grouped_sub:   "Mandeha amin'ny vondrona kely amin'ny vidiny ambany — programa voafaritra, tontolo tsara",
      places_left:   "toerana misy",
      places_few:    "toerana sisa",
      book_now:      "Mandahatra",
      group_price:   "Vidin'ny vondron'olona",
      group_incl:    "misy avokoa",
      services_tag:  "Izay aniana",
      services_h2:   "Voaomana avokoa ho anao",
      services_sub:  "Fanohanana feno, hatramin'ny hafatra voalohany ka hatramin'ny fiverenana",
      svc1_h: "Fiara 4×4 misy mpamily", svc1_p: "Toyota Land Cruiser vaovao, mpamily matoky miteny roa. Mazava ny làlana rehetra any Madagasikara.",
      svc2_h: "Toerana fatoriana voafidy", svc2_p: "Lodge manavanana, ecolodge any an-tsaha — efa voatokana, voatazana manokana ny kalitaony.",
      svc3_h: "Mpitarika telo fiteny FR/EN/MGA", svc3_p: "Mpifandray tokana miteny ny fiteninareo sy ny an'ny Malagasy — ho firesahana marina.",
      svc4_h: "Lalana voaomana manokana", svc4_p: "Dia tsirairay dia atao miaraka aminareo : fe-potoana, dinika, hetsika, tetibola — tsy misy hidy miafina.",
      reviews_tag:   "Niverina faly izy ireo",
      reviews_h2:    "Izay lazain'ny mpizaha tany",
      cta_h2:        "Vonona hanao ny Madagasikaranao?",
      cta_sub:       "Mifandraisa amiko mivantana — maimaimpoana ny fanombanana.",
      cta_btn:       "Hangataka fanombanana",
      contact_tag:   "Fifandraisana",
      contact_h2a:   "Aorienay",
      contact_h2b:   "ny dianao",
      contact_sub:   "Valiny voatampon'ny 24 ora — fanombanana maimaimpoana",
      form_h3:       "Fangatahana fanombanana maimaimpoana",
      form_intro:    "Fenoy ity fomba ity ary hovaliana anao ao anatin'ny 24 ora miaraka amin'ny vozon-kevitra manokana.",
      form_required: "Saha ilaina",
      f_name:        "Anarana feno", f_name_ph: "Rakoto Jean",
      f_email:       "Email",        f_email_ph: "rakoto@ohatra.com",
      f_phone:       "Lahatsoratra",  f_phone_ph: "+261 34 000 0000",
      f_travelers:   "Isan'ny mpizaha tany",
      f_date:        "Daty fandehanana kendrena",
      f_duration:    "Faharetan'ny dia",
      f_circuit:     "Dian-tany kendrena",
      f_pref:        "Fomba fifandraisana tiako",
      f_pref_email:  "Email", f_pref_wa: "WhatsApp", f_pref_call: "Antso",
      f_message:     "Hafatra / fanazavana", f_message_ph: "Lazao ny fanirianao, ny fetra, ny tetibola…",
      f_submit:      "Mandefa fangatahana",
      f_success_h:   "Nalefa ny hafatra!",
      f_success_p:   "Misaotra! Hovaliana anao ao anatin'ny 24 ora miaraka amin'ny vozon-kevitra manokana.",
      f_opt1: "Olona 1", f_opt2: "Olona 2", f_opt3: "Olona 3–4", f_opt4: "Olona 5–8", f_opt5: "Vondron'olona 9+",
      fd_opt1: "Latsaky ny 7 andro", fd_opt2: "7–10 andro", fd_opt3: "11–14 andro", fd_opt4: "15–21 andro", fd_opt5: "Mihoatra ny 21 andro",
      footer_tagline: "Antoko fizahantany manokana any Madagasikara. Mpitarika telo fiteny (FR/EN/MGA), avy any Nosy Be, mipetraka any Frantsa.",
      footer_circuits: "Dian-tany", footer_info: "Fampahalalana",
      footer_nl_h: "Mahareta ho aingam-panahy",
      footer_nl_p: "Mandray hevitra momba ny lalana sy daty vaovao ho an'ny vondron'olona.",
      footer_nl_ph: "email@anao.mg",
      footer_ml: "Fampahalalana ara-dalàna", footer_cgv: "Fepetra", footer_conf: "Tsiambaratelon'ny tontolo",
      copyright: "© 2026 Zenith Travel and Tours — Zo rehetra voatokana.",
      back_circuits: "Ny dian-tany rehetra",
      discover_also: "Jereo ihany koa",
      other_circuits: "Dian-tany hafa any Madagasikara",
      grouped_also: "Te-hanao dia manokana?",
      grouped_also_btn: "Hangataka dian-tany manokana",
      lang_fr: "FR", lang_en: "EN", lang_mg: "MG"
    }
  },

  /* ================================================================
     CIRCUITS — 6 default
  ================================================================ */
  circuits: [
    {
      id: "baobabs",
      slug: "circuit-baobabs",
      pill_fr: "Bestseller", pill_en: "Bestseller", pill_mg: "Tsara indrindra",
      duration_days: 7,
      location_fr: "Morondava", location_en: "Morondava", location_mg: "Morondava",
      price: 890,
      image: "https://images.unsplash.com/photo-1590856029826-c7a73142bbf1?w=700&q=80",
      hero_image: "https://images.unsplash.com/photo-1590856029826-c7a73142bbf1?w=1800&q=80",
      name_fr: "Allée des Baobabs & Morondava",
      name_en: "Avenue of the Baobabs & Morondava",
      name_mg: "Làlana Baobabs & Morondava",
      desc_fr: "Couchers de soleil légendaires face aux baobabs centenaires, pirogue sur le Tsiribihina, villages Betsimisaraka.",
      desc_en: "Legendary sunsets in front of centuries-old baobabs, dugout canoe on the Tsiribihina, Betsimisaraka villages.",
      desc_mg: "Fikarohana masoandro lehibe eo anoloan'ny baobaba, lakana eny amin'ny Tsiribihina, vohitra Betsimisaraka.",
      difficulty_fr: "Modérée", difficulty_en: "Moderate", difficulty_mg: "Antonony",
      best_period_fr: "Avr – Nov", best_period_en: "Apr – Nov", best_period_mg: "Avr – Nov",
      transport_fr: "4×4 + pirogue", transport_en: "4×4 + dugout", transport_mg: "4×4 + lakana",
      max_group: 8,
      gallery: [
        "https://images.unsplash.com/photo-1590856029826-c7a73142bbf1?w=800&q=80",
        "https://images.unsplash.com/photo-1551632811-561732d1e306?w=500&q=80",
        "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=500&q=80",
        "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=500&q=80",
        "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=500&q=80"
      ],
      days_fr: [
        { num: "J1", title: "Antananarivo → Morondava (vol)", desc: "Accueil à l'aéroport. Installation à l'hôtel, promenade au marché de Morondava. Dîner de bienvenue." },
        { num: "J2", title: "Allée des Baobabs — lever & coucher de soleil", desc: "Départ à l'aube pour les premiers rayons. Visite du village de Marofandilia. Coucher de soleil inoubliable." },
        { num: "J3", title: "Remontée du Tsiribihina en pirogue", desc: "Pirogue motorisée depuis Belo-sur-Tsiribihina. Caïmans, oiseaux, nuit sous les étoiles." },
        { num: "J4", title: "Navigation fluviale (suite)", desc: "Deuxième journée de pirogue. Baignade dans les rapides, pêcheurs Vezo, arrivée à Miandrivazo." },
        { num: "J5", title: "Baobabs Amoureux", desc: "Retour avec arrêt aux Baobabs Amoureux. Temps libre à Morondava, marché artisanal." },
        { num: "J6", title: "Mangroves & côte sauvage", desc: "Excursion en bateau dans les mangroves. Snorkeling, fruits de mer au coucher de soleil." },
        { num: "J7", title: "Morondava → Antananarivo", desc: "Dernier matin. Transfert aéroport pour vol retour." }
      ],
      days_en: [
        { num: "D1", title: "Antananarivo → Morondava (flight)", desc: "Airport welcome. Hotel check-in, stroll through Morondava market. Welcome dinner." },
        { num: "D2", title: "Avenue of Baobabs — sunrise & sunset", desc: "Dawn departure for the first rays on the baobabs. Visit Marofandilia village. Unforgettable sunset." },
        { num: "D3", title: "Tsiribihina River by dugout canoe", desc: "Motorised dugout from Belo-sur-Tsiribihina. Crocodiles, birds, sleeping under the stars." },
        { num: "D4", title: "River navigation (continued)", desc: "Second day on the river. Swimming in the rapids, Vezo fishermen, arrival in Miandrivazo." },
        { num: "D5", title: "Baobabs in Love", desc: "Return via the Baobabs in Love. Free time in Morondava, craft market." },
        { num: "D6", title: "Mangroves & wild coast", desc: "Boat trip through the mangroves. Snorkelling, seafood at sunset." },
        { num: "D7", title: "Morondava → Antananarivo", desc: "Last morning. Airport transfer for return flight." }
      ],
      incl_fr: ["Vol intérieur Tana ↔ Morondava", "6 nuits en hébergement sélectionné", "Transport 4×4 avec chauffeur francophone", "Pirogue motorisée (2 jours)", "Tous les transferts", "Droits d'entrée", "Guide francophone terrain"],
      incl_en: ["Domestic flight Tana ↔ Morondava", "6 nights in selected accommodation", "4×4 transport with French-speaking driver", "Motorised dugout (2 days)", "All transfers", "Entry fees", "Local English-speaking guide"],
      excl_fr: ["Vol international", "Visa d'entrée", "Repas", "Assurance voyage", "Dépenses personnelles"],
      excl_en: ["International flight", "Entry visa", "Meals", "Travel insurance", "Personal expenses"]
    },
    {
      id: "nosybe",
      slug: "circuit-nosybe",
      pill_fr: "Plage & Nature", pill_en: "Beach & Nature", pill_mg: "Moron-dranomasina & Natiora",
      duration_days: 10,
      location_fr: "Nosy Be", location_en: "Nosy Be", location_mg: "Nosy Be",
      price: 1150,
      image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=700&q=80",
      hero_image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1800&q=80",
      name_fr: "Nosy Be & Archipel des Îles",
      name_en: "Nosy Be & Island Archipelago",
      name_mg: "Nosy Be & Ireo Nosy Madinika",
      desc_fr: "Plongée à Nosy Tanikely, lémuriens à Nosy Komba, croisière en boutre, plages de sable blanc immaculé.",
      desc_en: "Diving at Nosy Tanikely, lemurs at Nosy Komba, dhow cruise, pristine white sand beaches.",
      desc_mg: "Milomano any Nosy Tanikely, gidro any Nosy Komba, sambo boutre, moron-dranomasina fotsy.",
      difficulty_fr: "Facile", difficulty_en: "Easy", difficulty_mg: "Mora",
      best_period_fr: "Mai – Nov", best_period_en: "May – Nov", best_period_mg: "Mai – Nov",
      transport_fr: "4×4 + bateau + boutre", transport_en: "4×4 + boat + dhow", transport_mg: "4×4 + sambo + boutre",
      max_group: 8,
      gallery: [
        "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800&q=80",
        "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=500&q=80",
        "https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=500&q=80",
        "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=500&q=80",
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&q=80"
      ],
      days_fr: [
        { num: "J1", title: "Antananarivo → Nosy Be (vol)", desc: "Arrivée à l'aéroport Fascene. Installation au lodge. Balade sur la plage au coucher de soleil." },
        { num: "J2", title: "Tour de l'île en 4×4", desc: "Mont Passot et ses lacs sacrés, plantation de ylang-ylang, marché de Hell-Ville." },
        { num: "J3", title: "Nosy Tanikely — Plongée & Snorkeling", desc: "Réserve marine : tortues, raies, poissons-perroquets, coraux multicolores." },
        { num: "J4", title: "Nosy Komba — Lémuriens & Village", desc: "Forêt primaire, lémuriens à queue noire, village artisanal d'Ampangorina." },
        { num: "J5", title: "Journée libre à Nosy Be", desc: "Plage, spa, plongée supplémentaire ou vélo selon vos envies." },
        { num: "J6–J7", title: "Croisière boutre vers Nosy Mitsio", desc: "Navigation en boutre traditionnel. Bivouac sur plage déserte, pêche au lever du soleil." },
        { num: "J8", title: "Plantation & Distillerie", desc: "Visite d'une plantation de ylang-ylang et dégustation de rhum arrangé artisanal." },
        { num: "J9", title: "Nosy Sakatia — Plongée de nuit", desc: "Hippocampes, pieuvres, plongée nocturne pour les aventuriers (optionnel)." },
        { num: "J10", title: "Nosy Be → Antananarivo", desc: "Dernier matin. Transfert aéroport et vol retour." }
      ],
      days_en: [
        { num: "D1", title: "Antananarivo → Nosy Be (flight)", desc: "Arrival at Fascene airport. Lodge check-in. Beach walk at sunset." },
        { num: "D2", title: "Island tour by 4×4", desc: "Mount Passot and its sacred lakes, ylang-ylang plantation, Hell-Ville market." },
        { num: "D3", title: "Nosy Tanikely — Diving & Snorkelling", desc: "Marine reserve: sea turtles, rays, parrotfish, multicoloured corals." },
        { num: "D4", title: "Nosy Komba — Lemurs & Village", desc: "Primary forest, black lemurs, artisan village of Ampangorina." },
        { num: "D5", title: "Free day on Nosy Be", desc: "Beach, spa, extra dive or cycling as you wish." },
        { num: "D6–D7", title: "Dhow cruise to Nosy Mitsio", desc: "Sailing on a traditional dhow. Camping on a deserted beach, fishing at sunrise." },
        { num: "D8", title: "Plantation & Distillery", desc: "Visit a ylang-ylang plantation and taste artisan rum." },
        { num: "D9", title: "Nosy Sakatia — Night dive", desc: "Seahorses, octopus, night diving for adventurers (optional)." },
        { num: "D10", title: "Nosy Be → Antananarivo", desc: "Last morning. Airport transfer and return flight." }
      ],
      incl_fr: ["Vol intérieur Tana ↔ Nosy Be", "9 nuits en hébergement sélectionné", "Transport 4×4", "Bateaux et pirogues", "Croisière boutre 2j/1n", "Droits d'entrée réserves", "Guide francophone"],
      incl_en: ["Domestic flight Tana ↔ Nosy Be", "9 nights selected accommodation", "4×4 transport", "All boats & canoes", "2-day dhow cruise", "Reserve entry fees", "English-speaking guide"],
      excl_fr: ["Vol international", "Visa", "Équipement plongée", "Repas", "Assurance voyage"],
      excl_en: ["International flight", "Visa", "Diving equipment", "Meals", "Travel insurance"]
    },
    {
      id: "tsingy",
      slug: "circuit-tsingy",
      pill_fr: "UNESCO", pill_en: "UNESCO", pill_mg: "UNESCO",
      duration_days: 12,
      location_fr: "Bemaraha", location_en: "Bemaraha", location_mg: "Bemaraha",
      price: 1380,
      image: "https://images.unsplash.com/photo-1548013146-72479768bada?w=700&q=80",
      hero_image: "https://images.unsplash.com/photo-1548013146-72479768bada?w=1800&q=80",
      name_fr: "Tsingy de Bemaraha",
      name_en: "Tsingy de Bemaraha",
      name_mg: "Tsingy de Bemaraha",
      desc_fr: "Via ferrata dans les forêts de calcaire classées UNESCO, nuits en lodge de brousse, lémuriens sifaka danseurs.",
      desc_en: "Via ferrata through UNESCO limestone forests, bush lodge nights, dancing sifaka lemurs.",
      desc_mg: "Via ferrata amin'ny akazan-dalitra UNESCO, alina any an-tsaha, gidro sifaka mandihy.",
      difficulty_fr: "Sportive", difficulty_en: "Sporty", difficulty_mg: "Mahery",
      best_period_fr: "Avr – Nov", best_period_en: "Apr – Nov", best_period_mg: "Avr – Nov",
      transport_fr: "4×4 + pirogue", transport_en: "4×4 + dugout", transport_mg: "4×4 + lakana",
      max_group: 6,
      gallery: [
        "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80",
        "https://images.unsplash.com/photo-1590856029826-c7a73142bbf1?w=500&q=80",
        "https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=500&q=80",
        "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=500&q=80",
        "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=500&q=80"
      ],
      days_fr: [
        { num: "J1", title: "Antananarivo → Morondava (vol)", desc: "Arrivée à Morondava, installation, briefing circuit." },
        { num: "J2", title: "Morondava → Bekopaka (4×4 + bac + pirogue)", desc: "Route latérite, traversée du Manambolo, lodge à Bekopaka." },
        { num: "J3", title: "Grands Tsingy — secteur Nord", desc: "Via ferrata, passerelles suspendues, grottes calcaires, vue panoramique." },
        { num: "J4", title: "Grands Tsingy — secteur Sud", desc: "Zone sauvage, lémuriens sifaka et caméléons endémiques." },
        { num: "J5", title: "Petits Tsingy & Gorges du Manambolo", desc: "Exploration des Petits Tsingy, descente en pirogue dans les gorges." },
        { num: "J6", title: "Bekopaka → Morondava", desc: "Retour, arrêt aux Baobabs Amoureux." },
        { num: "J7", title: "Allée des Baobabs — lever de soleil", desc: "Premiers rayons sur les baobabs géants, village de Marofandilia." },
        { num: "J8–J9", title: "Canal des Pangalanes — Pirogue 2 jours", desc: "Navigation Tsiribihina, bivouac, caïmans et oiseaux endémiques." },
        { num: "J10", title: "Kirindy — Forêt sèche & faune nocturne", desc: "Réserve de Kirindy, safari nocturne : fossas, lémuriens, geckos géants." },
        { num: "J11", title: "Kirindy → Morondava", desc: "Retour, plage, marché artisanal, dîner de clôture." },
        { num: "J12", title: "Morondava → Antananarivo", desc: "Vol retour et connexion internationale." }
      ],
      days_en: [
        { num: "D1", title: "Antananarivo → Morondava (flight)", desc: "Arrival, hotel check-in, circuit briefing." },
        { num: "D2", title: "Morondava → Bekopaka (4×4 + ferry + dugout)", desc: "Laterite road, Manambolo crossing, Bekopaka lodge." },
        { num: "D3", title: "Great Tsingy — North sector", desc: "Via ferrata, suspension bridges, limestone caves, panoramic views." },
        { num: "D4", title: "Great Tsingy — South sector", desc: "Wilder zone, sifaka lemurs and endemic chameleons." },
        { num: "D5", title: "Small Tsingy & Manambolo Gorges", desc: "Exploration of Small Tsingy, dugout descent through the gorges." },
        { num: "D6", title: "Bekopaka → Morondava", desc: "Return, stop at the Baobabs in Love." },
        { num: "D7", title: "Avenue of Baobabs — sunrise", desc: "First light on the giant baobabs, Marofandilia village." },
        { num: "D8–D9", title: "Pangalanes Canal — 2 days by dugout", desc: "Tsiribihina navigation, bivouac, crocodiles and endemic birds." },
        { num: "D10", title: "Kirindy — dry forest & night safari", desc: "Kirindy reserve, night safari: fossas, lemurs, giant geckos." },
        { num: "D11", title: "Kirindy → Morondava", desc: "Return, beach, craft market, farewell dinner." },
        { num: "D12", title: "Morondava → Antananarivo", desc: "Return flight and international connection." }
      ],
      incl_fr: ["Vol intérieur Tana ↔ Morondava", "11 nuits hébergement", "Transport 4×4 + pirogues", "Équipement via ferrata", "Droits d'entrée UNESCO", "Guide naturaliste", "Safari nocturne Kirindy"],
      incl_en: ["Domestic flight Tana ↔ Morondava", "11 nights accommodation", "4×4 + dugout transport", "Via ferrata equipment", "UNESCO entry fees", "Naturalist guide", "Kirindy night safari"],
      excl_fr: ["Vol international", "Visa", "Repas", "Assurance voyage", "Dépenses personnelles"],
      excl_en: ["International flight", "Visa", "Meals", "Travel insurance", "Personal expenses"]
    },
    {
      id: "sud",
      slug: "circuit-sud",
      pill_fr: "Aventure", pill_en: "Adventure", pill_mg: "Aventora",
      duration_days: 14,
      location_fr: "Toliara", location_en: "Toliara", location_mg: "Toliara",
      price: 1490,
      image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=700&q=80",
      hero_image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1800&q=80",
      name_fr: "Grand Sud Sauvage",
      name_en: "Wild Grand South",
      name_mg: "Atsimo lehibe malalantsoa",
      desc_fr: "Canyons de l'Isalo, forêt épineuse, lagon d'Ifaty, pirogues Vezo — le bout du monde en toute sérénité.",
      desc_en: "Isalo canyons, spiny forest, Ifaty lagoon, Vezo dugouts — the edge of the world in total serenity.",
      desc_mg: "Canyon Isalo, alan'ny tsilo, lac Ifaty, lakana Vezo — ny faran'izao tontolo izao amin'ny fiadanana.",
      difficulty_fr: "Modérée à sportive", difficulty_en: "Moderate to sporty", difficulty_mg: "Antonony ka mahery",
      best_period_fr: "Avr – Nov", best_period_en: "Apr – Nov", best_period_mg: "Avr – Nov",
      transport_fr: "4×4 + pirogue Vezo", transport_en: "4×4 + Vezo dugout", transport_mg: "4×4 + lakana Vezo",
      max_group: 8,
      gallery: [
        "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80",
        "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=500&q=80",
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&q=80",
        "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500&q=80",
        "https://images.unsplash.com/photo-1590856029826-c7a73142bbf1?w=500&q=80"
      ],
      days_fr: [
        { num: "J1", title: "Antananarivo → Tuléar (vol)", desc: "Arrivée, transfert hôtel, marché et port de pêche Vezo." },
        { num: "J2", title: "Ifaty — Lagon & Pirogue Vezo", desc: "Lagon d'Ifaty, pirogue traditionnelle, snorkeling sur le récif." },
        { num: "J3", title: "Forêt épineuse de Reniala", desc: "Euphorbes, aloès, baobabs endémiques, oiseaux rares." },
        { num: "J4", title: "Ifaty → Isalo (4×4)", desc: "Route à travers les paysages mahafaly et bara. Arrivée à l'Isalo." },
        { num: "J5", title: "Isalo — Canyon des Singes", desc: "Randonnée, piscine naturelle de la Nymphe, lémuriens bruns." },
        { num: "J6", title: "Isalo — Piscines Bleue & Rouge", desc: "Piscines naturelles, fenêtres d'Isalo, panoramas vertigineux." },
        { num: "J7", title: "Ambalavao — Papier Antaimoro", desc: "Atelier de papier artisanal fabriqué à la main depuis des siècles." },
        { num: "J8", title: "Village Bara", desc: "Rencontre avec la communauté Bara, dressage de zébus." },
        { num: "J9–J10", title: "Réserve d'Anja — Lémuriens Cattas", desc: "Cattas en liberté sur les rochers granitiques." },
        { num: "J11", title: "Retour vers Tuléar", desc: "Piste rouge, villages de cases en terre, semi-désert." },
        { num: "J12", title: "Tuléar — Journée libre", desc: "Plage de Batterie, marché artisanal, boutre au coucher de soleil." },
        { num: "J13", title: "Anakao — Village Vezo", desc: "Village de pêcheurs préservé, cimetières mahafaly totémiques." },
        { num: "J14", title: "Tuléar → Antananarivo", desc: "Vols de retour." }
      ],
      days_en: [
        { num: "D1", title: "Antananarivo → Toliara (flight)", desc: "Arrival, hotel transfer, Vezo fish market and harbour." },
        { num: "D2", title: "Ifaty — Lagoon & Vezo dugout", desc: "Ifaty lagoon, traditional dugout, reef snorkelling." },
        { num: "D3", title: "Reniala spiny forest", desc: "Euphorbias, aloes, endemic baobabs, rare birds." },
        { num: "D4", title: "Ifaty → Isalo (4×4)", desc: "Road through Mahafaly and Bara landscapes. Arrival at Isalo." },
        { num: "D5", title: "Isalo — Monkey Canyon", desc: "Hike, natural pool of the Nymph, brown lemurs." },
        { num: "D6", title: "Isalo — Blue & Red pools", desc: "Natural pools, Isalo windows, vertiginous panoramas." },
        { num: "D7", title: "Ambalavao — Antaimoro paper", desc: "Centuries-old handmade paper workshop." },
        { num: "D8", title: "Bara village", desc: "Meeting the Bara community, zebu herding demonstration." },
        { num: "D9–D10", title: "Anja Reserve — Ring-tailed lemurs", desc: "Free-ranging ring-tails on granite outcrops." },
        { num: "D11", title: "Return to Toliara", desc: "Red laterite track, earth huts, semi-desert." },
        { num: "D12", title: "Toliara — Free day", desc: "Battery beach, craft market, sunset dhow." },
        { num: "D13", title: "Anakao — Vezo village", desc: "Preserved fishing village, totemic Mahafaly tombs." },
        { num: "D14", title: "Toliara → Antananarivo", desc: "Return flights." }
      ],
      incl_fr: ["Vol intérieur Tana ↔ Tuléar", "13 nuits hébergement", "Transport 4×4", "Pirogues et bateaux", "Droits d'entrée", "Guide naturaliste", "Nuit chez l'habitant"],
      incl_en: ["Domestic flight Tana ↔ Toliara", "13 nights accommodation", "4×4 transport", "Dugouts and boats", "Entry fees", "Naturalist guide", "Local homestay night"],
      excl_fr: ["Vol international", "Visa", "Repas", "Assurance voyage", "Équipement randonnée"],
      excl_en: ["International flight", "Visa", "Meals", "Travel insurance", "Hiking equipment"]
    },
    {
      id: "highlands",
      slug: "circuit-highlands",
      pill_fr: "Culture", pill_en: "Culture", pill_mg: "Kolontsaina",
      duration_days: 9,
      location_fr: "Hauts Plateaux", location_en: "Highlands", location_mg: "Tany avo",
      price: 760,
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80",
      hero_image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1800&q=80",
      name_fr: "Highlands & Antananarivo",
      name_en: "Highlands & Antananarivo",
      name_mg: "Tany avo & Antananarivo",
      desc_fr: "Marchés d'Ambatolampy, rizières en terrasses d'Ambositra, artisanat betsileo, train colonial FCE.",
      desc_en: "Ambatolampy markets, Ambositra terrace rice fields, Betsileo crafts, FCE colonial train.",
      desc_mg: "Tsena Ambatolampy, vary an-tsasany Ambositra, tantsaha betsileo, lamasinina FCE.",
      difficulty_fr: "Facile", difficulty_en: "Easy", difficulty_mg: "Mora",
      best_period_fr: "Toute l'année", best_period_en: "Year-round", best_period_mg: "Manontolo ny taona",
      transport_fr: "4×4 + transferts", transport_en: "4×4 + transfers", transport_mg: "4×4 + fifindrana",
      max_group: 10,
      gallery: [
        "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
        "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=500&q=80",
        "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=500&q=80",
        "https://images.unsplash.com/photo-1551632811-561732d1e306?w=500&q=80",
        "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=500&q=80"
      ],
      days_fr: [
        { num: "J1", title: "Arrivée à Antananarivo", desc: "Accueil, première balade en ville haute, vue sur la Rova." },
        { num: "J2", title: "Antananarivo — Rova & Musées", desc: "Rova d'Ambohimanga (UNESCO), musée de l'Académie, marché Zoma." },
        { num: "J3", title: "Tana → Antsirabe", desc: "Départ sur la RN7, marché des chaudrons d'Ambatolampy, Antsirabe." },
        { num: "J4", title: "Antsirabe — Ville thermale & Ateliers", desc: "Pousse-pousse, jouets recyclés, bijoux en corne, bains thermaux." },
        { num: "J5", title: "Antsirabe → Ambositra", desc: "Route panoramique, ateliers de marqueterie et tissage betsileo." },
        { num: "J6", title: "Ambositra → Fianarantsoa", desc: "Rizières à couper le souffle, ville historique classée." },
        { num: "J7", title: "Fianarantsoa — Train FCE & Vignobles", desc: "Train colonial FCE, caves viticoles coopératives." },
        { num: "J8", title: "Retour Tana via RN7", desc: "Paysages highlands, arrêts photos, marché de Betafo." },
        { num: "J9", title: "Antananarivo — Départ", desc: "Shopping artisanal, transfert aéroport." }
      ],
      days_en: [
        { num: "D1", title: "Arrival in Antananarivo", desc: "Welcome, first walk through the upper town, view of the Rova." },
        { num: "D2", title: "Antananarivo — Rova & Museums", desc: "Ambohimanga Rova (UNESCO), Academy Museum, Zoma market." },
        { num: "D3", title: "Tana → Antsirabe", desc: "Departure on RN7, Ambatolampy aluminium cauldron market." },
        { num: "D4", title: "Antsirabe — Thermal town & Workshops", desc: "Rickshaw ride, recycled toys, horn jewellery, thermal baths." },
        { num: "D5", title: "Antsirabe → Ambositra", desc: "Scenic road, marquetry and Betsileo weaving workshops." },
        { num: "D6", title: "Ambositra → Fianarantsoa", desc: "Breathtaking rice terraces, listed historic town." },
        { num: "D7", title: "Fianarantsoa — FCE Train & Vineyards", desc: "Colonial FCE train, cooperative wine cellars." },
        { num: "D8", title: "Return to Tana via RN7", desc: "Highland landscapes, photo stops, Betafo market." },
        { num: "D9", title: "Antananarivo — Departure", desc: "Craft shopping, airport transfer." }
      ],
      incl_fr: ["Toutes les nuits hôtels", "Transport 4×4", "Guide culturel francophone", "Entrée Ambohimanga UNESCO", "Train FCE", "Visites ateliers artisans", "Transferts aéroport"],
      incl_en: ["All hotel nights", "4×4 transport", "Cultural French-speaking guide", "Ambohimanga UNESCO entry", "FCE train", "Artisan workshop visits", "Airport transfers"],
      excl_fr: ["Vol international", "Visa", "Repas", "Assurance", "Bains thermaux (option)"],
      excl_en: ["International flight", "Visa", "Meals", "Insurance", "Thermal baths (optional)"]
    },
    {
      id: "grande-ile",
      slug: "circuit-grande-ile",
      pill_fr: "Épique", pill_en: "Epic", pill_mg: "Malazan'i Madagasikara",
      duration_days: 21,
      location_fr: "Tour de l'île", location_en: "Full island tour", location_mg: "Manodidina ny Nosy",
      price: 2450,
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=700&q=80",
      hero_image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1800&q=80",
      name_fr: "La Grande Île Intégrale",
      name_en: "The Complete Big Island",
      name_mg: "Madagasikara Manontolo",
      desc_fr: "La traversée complète Nord-Sud : toutes les merveilles de Madagascar en une seule épopée inoubliable.",
      desc_en: "The complete North-South crossing: every wonder of Madagascar in one unforgettable journey.",
      desc_mg: "Ny fihaingoana avy avaratra ka hatramin'ny atsimo: ny fahagagana rehetra an'i Madagasikara.",
      difficulty_fr: "Modérée", difficulty_en: "Moderate", difficulty_mg: "Antonony",
      best_period_fr: "Avr – Nov", best_period_en: "Apr – Nov", best_period_mg: "Avr – Nov",
      transport_fr: "4×4 + vols intérieurs + bateau", transport_en: "4×4 + domestic flights + boat", transport_mg: "4×4 + sidina + sambo",
      max_group: 6,
      gallery: [
        "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80",
        "https://images.unsplash.com/photo-1590856029826-c7a73142bbf1?w=500&q=80",
        "https://images.unsplash.com/photo-1548013146-72479768bada?w=500&q=80",
        "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=500&q=80",
        "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=500&q=80"
      ],
      days_fr: [
        { num: "J1–J3",   title: "Nosy Be & Archipel",                desc: "Plongée Nosy Tanikely, lémuriens Nosy Komba, croisière coucher de soleil." },
        { num: "J4",      title: "Nosy Be → Tana → Morondava",        desc: "Vols intérieurs de connexion, installation à Morondava." },
        { num: "J5–J6",   title: "Tsingy de Bemaraha",                desc: "Via ferrata Grands et Petits Tsingy, gorges du Manambolo." },
        { num: "J7",      title: "Allée des Baobabs",                  desc: "Lever de soleil sur les baobabs géants, pirogue sur le canal." },
        { num: "J8",      title: "Kirindy — Forêt sèche",             desc: "Réserve de Kirindy, safari nocturne, fossas et lémuriens." },
        { num: "J9",      title: "Morondava → Antananarivo",           desc: "Vol Tana, journée de transition, visite Rova." },
        { num: "J10–J11", title: "Highlands",                          desc: "RN7 : marchés, ateliers artisans, rizières en terrasses." },
        { num: "J12–J13", title: "Fianarantsoa & Train FCE",           desc: "Train colonial, vignobles, ville historique." },
        { num: "J14–J15", title: "Isalo",                              desc: "Canyons, piscines naturelles, randonnées." },
        { num: "J16",     title: "Réserve d'Anja",                    desc: "Lémuriens cattas dans la réserve communautaire." },
        { num: "J17–J18", title: "Ifaty & Lagon",                     desc: "Pirogue Vezo, lagon turquoise, snorkeling." },
        { num: "J19",     title: "Forêt épineuse de Reniala",          desc: "Faune et flore endémiques du Grand Sud." },
        { num: "J20",     title: "Tuléar — Journée libre",             desc: "Plage, marché, boutre, dîner de clôture." },
        { num: "J21",     title: "Tuléar → Tana → Départ",            desc: "Vols de retour, fin de l'épopée." }
      ],
      days_en: [
        { num: "D1–D3",   title: "Nosy Be & Archipelago",               desc: "Nosy Tanikely diving, Nosy Komba lemurs, sunset cruise." },
        { num: "D4",      title: "Nosy Be → Tana → Morondava",          desc: "Connecting domestic flights, Morondava check-in." },
        { num: "D5–D6",   title: "Tsingy de Bemaraha",                  desc: "Via ferrata, Manambolo gorges." },
        { num: "D7",      title: "Avenue of the Baobabs",               desc: "Sunrise on the giant baobabs, canal dugout." },
        { num: "D8",      title: "Kirindy — dry forest",                desc: "Kirindy reserve, night safari, fossas and lemurs." },
        { num: "D9",      title: "Morondava → Antananarivo",            desc: "Flight to Tana, Rova visit." },
        { num: "D10–D11", title: "Highlands",                           desc: "RN7: markets, artisan workshops, rice terraces." },
        { num: "D12–D13", title: "Fianarantsoa & FCE Train",            desc: "Colonial train, vineyards, historic town." },
        { num: "D14–D15", title: "Isalo",                               desc: "Canyons, natural pools, hikes." },
        { num: "D16",     title: "Anja Reserve",                        desc: "Ring-tailed lemurs in the community reserve." },
        { num: "D17–D18", title: "Ifaty & Lagoon",                      desc: "Vezo dugout, turquoise lagoon, snorkelling." },
        { num: "D19",     title: "Reniala spiny forest",                desc: "Endemic Grand South fauna and flora." },
        { num: "D20",     title: "Toliara — Free day",                  desc: "Beach, market, dhow, farewell dinner." },
        { num: "D21",     title: "Toliara → Tana → Departure",          desc: "Return flights, end of the journey." }
      ],
      incl_fr: ["3 vols intérieurs inclus", "20 nuits hébergement", "Transport 4×4 et bateaux", "Via ferrata, safaris", "Droits d'entrée sites classés", "Guide expert francophone", "Assistance 24h/24"],
      incl_en: ["3 domestic flights", "20 nights accommodation", "4×4 + boat transport", "Via ferrata, safaris", "All classified site fees", "Expert English-speaking guide", "24h assistance"],
      excl_fr: ["Vol international", "Visa", "Repas", "Assurance voyage", "Dépenses personnelles"],
      excl_en: ["International flight", "Visa", "Meals", "Travel insurance", "Personal expenses"]
    }
  ],

  /* ================================================================
     VOYAGES ORGANISÉS
  ================================================================ */
  grouped: [
    {
      id: "g1",
      name_fr: "Allée des Baobabs & Côte Ouest",
      name_en: "Avenue of the Baobabs & West Coast",
      name_mg: "Làlana Baobabs & Moron'ny Atsinanana",
      image: "https://images.unsplash.com/photo-1590856029826-c7a73142bbf1?w=700&q=80",
      day: "12", month_fr: "Juin 2026", month_en: "June 2026", month_mg: "Jona 2026",
      duration_fr: "8 jours", duration_en: "8 days", duration_mg: "8 andro",
      departure_date: "2026-06-12",
      price: 650,
      max_places: 10,
      taken: 7,
      incl_fr: "Hébergements inclus · 4×4 partagé",
      incl_en: "Accommodation included · Shared 4×4",
      incl_mg: "Toerana fatoriana · 4×4 miaraka"
    },
    {
      id: "g2",
      name_fr: "Nosy Be Essentiel — Îles & Récifs",
      name_en: "Nosy Be Essential — Islands & Reefs",
      name_mg: "Nosy Be — Nosy sy Reef",
      image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=700&q=80",
      day: "05", month_fr: "Juil 2026", month_en: "July 2026", month_mg: "Jolay 2026",
      duration_fr: "7 jours", duration_en: "7 days", duration_mg: "7 andro",
      departure_date: "2026-07-05",
      price: 780,
      max_places: 8,
      taken: 3,
      incl_fr: "Hébergements inclus · Bateaux partagés",
      incl_en: "Accommodation included · Shared boats",
      incl_mg: "Toerana fatoriana · Sambo miaraka"
    },
    {
      id: "g3",
      name_fr: "Highlands & RN7 — Escapade Culturelle",
      name_en: "Highlands & RN7 — Cultural Escape",
      name_mg: "Tany avo & RN7 — Kolontsaina",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80",
      day: "20", month_fr: "Août 2026", month_en: "Aug 2026", month_mg: "Aogositra 2026",
      duration_fr: "9 jours", duration_en: "9 days", duration_mg: "9 andro",
      departure_date: "2026-08-20",
      price: 590,
      max_places: 12,
      taken: 2,
      incl_fr: "Hébergements inclus · 4×4 partagé",
      incl_en: "Accommodation included · Shared 4×4",
      incl_mg: "Toerana fatoriana · 4×4 miaraka"
    },
    {
      id: "g4",
      name_fr: "Grand Sud — Isalo & Lagon d'Ifaty",
      name_en: "Grand South — Isalo & Ifaty Lagoon",
      name_mg: "Atsimo lehibe — Isalo & Lac Ifaty",
      image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=700&q=80",
      day: "15", month_fr: "Sept 2026", month_en: "Sept 2026", month_mg: "Septambra 2026",
      duration_fr: "11 jours", duration_en: "11 days", duration_mg: "11 andro",
      departure_date: "2026-09-15",
      price: 870,
      max_places: 10,
      taken: 9,
      incl_fr: "Hébergements inclus · Pirogue Vezo incluse",
      incl_en: "Accommodation included · Vezo dugout included",
      incl_mg: "Toerana fatoriana · Lakana Vezo"
    }
  ],

  /* ================================================================
     TESTIMONIALS (shared across languages)
  ================================================================ */
  testimonials: [
    {
      stars: 5,
      text_fr: "Dix jours sur la RN7 et je suis rentré transformé. Chaque détail était pensé, chaque étape était juste. Une guide exceptionnelle, disponible et passionnée.",
      text_en: "Ten days on the RN7 and I came back transformed. Every detail was considered, every stop was just right. An exceptional, available and passionate guide.",
      text_mg: "Folo andro teo amin'ny RN7 ary niverina niova aho. Tsara noheverina ny antsipiriany tsirairay. Mpitarika tsy mahazatra, tia ny raharaha.",
      name: "Marc Léonard",
      origin_fr: "Lyon — Circuit RN7, 10 jours",
      origin_en: "Lyon — RN7 tour, 10 days",
      origin_mg: "Lyon — Dian-tany RN7, 10 andro",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80"
    },
    {
      stars: 5,
      text_fr: "Nous voulions quelque chose d'authentique pour fêter nos 40 ans de mariage. Le circuit Nosy Be était parfait — rythme respecté, logistique impeccable, vraie chaleur humaine.",
      text_en: "We wanted something authentic to celebrate our 40th wedding anniversary. The Nosy Be tour was perfect — pace respected, impeccable logistics, real warmth.",
      text_mg: "Nety tanteraka ny dian-tany Nosy Be — fanajana ny faharetana, tsara ny fitantanana, mafana ny fifandraisana.",
      name: "Chantal & Pierre Mercier",
      origin_fr: "Bordeaux — Nosy Be, 12 jours",
      origin_en: "Bordeaux — Nosy Be, 12 days",
      origin_mg: "Bordeaux — Nosy Be, 12 andro",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80"
    },
    {
      stars: 5,
      text_fr: "Tsingy de Bemaraha avec Zenith — une expérience hors du temps. Organisation parfaite malgré les contraintes logistiques. Je recommande sans hésiter.",
      text_en: "Tsingy de Bemaraha with Zenith — a timeless experience. Perfect organisation despite the logistical challenges. I recommend without hesitation.",
      text_mg: "Tsingy de Bemaraha niaraka tamin'i Zenith — traikefa tsy azo adino. Tsara ny fitantanana na dia sarotra aza. Manoro tanteraka aho.",
      name: "Sophie Blanchard",
      origin_fr: "Paris — Tsingy, 12 jours",
      origin_en: "Paris — Tsingy, 12 days",
      origin_mg: "Paris — Tsingy, 12 andro",
      avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&q=80"
    }
  ]
};

/* ---- Load: returns saved admin data or defaults ---- */
function loadSiteData() {
  try {
    const saved = localStorage.getItem('zenith_data');
    if (saved) return JSON.parse(saved);
  } catch(e) {}
  return JSON.parse(JSON.stringify(ZENITH_DEFAULT_DATA));
}

function saveSiteData(data) {
  localStorage.setItem('zenith_data', JSON.stringify(data));
}

function resetSiteData() {
  localStorage.removeItem('zenith_data');
}

/* ---- Language helpers ---- */
function getLang() {
  return localStorage.getItem('zenith_lang') || 'fr';
}
function setLang(l) {
  localStorage.setItem('zenith_lang', l);
}
function t(key) {
  const data = loadSiteData();
  const lang = getLang();
  return (data.i18n[lang] && data.i18n[lang][key]) || (data.i18n['fr'] && data.i18n['fr'][key]) || key;
}
function tField(obj, field) {
  const lang = getLang();
  return obj[field + '_' + lang] || obj[field + '_fr'] || obj[field] || '';
}
